-- Create staging table to load raw CSV
CREATE TABLE staging_sites (
    sitecode TEXT,
    shorttitle TEXT,
    title TEXT,
    sitetype TEXT,
    subtype TEXT,
    stage TEXT,
    projcode TEXT,
    projecttitle TEXT,
    longitude NUMERIC,
    latitude NUMERIC,
    easting NUMERIC,
    northing NUMERIC,
    mgazone TEXT,
    commodities TEXT,
    commoditygroupname TEXT,
    targetgroupname TEXT,
    maplabelname TEXT,
    includecommodityflag TEXT,
    mapcommodities TEXT,
    activeflag TEXT,
    symbol TEXT,
    symbolstatus TEXT,
    mapseries TEXT,
    confidentiality TEXT,
    mapsheetno100k TEXT,
    mapsheetname100k TEXT,
    mapsheetno250k TEXT,
    mapsheetname250k TEXT,
    lganame TEXT,
    developmentregion TEXT,
    districtno TEXT,
    districtname TEXT,
    tectonicunit TEXT,
    extractdate TEXT
);